TemplateBody:
  AWSTemplateFormatVersion: 2010-09-09
  Description: >-
    IAM role for serviceaccount "kube-system/aws-node" [created and managed by
    eksctl]
  Resources:
    Role1:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Action:
                - 'sts:AssumeRoleWithWebIdentity'
              Condition:
                StringEquals:
                  'oidc.eks.us-west-2.amazonaws.com/id/4B64703AA5DFE937208D55D595079068:aud': sts.amazonaws.com
                  'oidc.eks.us-west-2.amazonaws.com/id/4B64703AA5DFE937208D55D595079068:sub': 'system:serviceaccount:kube-system:aws-node'
              Effect: Allow
              Principal:
                Federated: >-
                  arn:aws:iam::867975079432:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/4B64703AA5DFE937208D55D595079068
          Version: 2012-10-17
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
  Outputs:
    Role1:
      Value: !GetAtt Role1.Arn
StagesAvailable:
  - Original
  - Processed
