
# how to run
#  aws cloudformation deploy \
#  --template-file aws/infra-eks.yml \
#  --tags project=udacapstone \
#  --stack-name "udacapstone-infra" \
#  --parameter-overrides ID="45ea76tu"

Description: >
  UdaInventory backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaInventory-${ID}
      GroupDescription: Allow port 22 and port 8000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: prod
      Version: '1.18'
      RoleArn: >-
        arn:aws:iam::867975079432:role/uda-eks-service-role
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !GetAtt InstanceSecurityGroup.GroupId
        SubnetIds:
          - subnet-034bd6e22be82c212
          - subnet-0440cc0249bb8a376
          - subnet-073cdb8f1f79d82ab
          - subnet-07c942c9d836c1f44