"""empty message

Revision ID: 36587251700c
Revises: 80534f9a5e60
Create Date: 2021-01-05 21:34:15.258305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36587251700c'
down_revision = '80534f9a5e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'goods', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    # ### end Alembic commands ###
