"""empty message

Revision ID: db4a79f9f9c2
Revises: f52ebe64d2f1
Create Date: 2021-01-05 21:21:58.778695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4a79f9f9c2'
down_revision = 'f52ebe64d2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'goods', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    # ### end Alembic commands ###
