
# how to run
#  aws cloudformation deploy \
#  --template-file aws/eks.yml \
#  --tags project=udacapstone \
#  --stack-name "udacapstone-infra" \
#  --parameter-overrides ID="45ea76tu" myEnvName="UdaCloudDevOpsCapstone"

Description: >
  UdaInventory backend stack.

Parameters:
  myEnvName:
    Description: An environment name that will be prefixed to resource names
    Type: String

#  ID:
#    Description: Unique identifier.
#    Type: String

Resources:
  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      #Name: prod
      Version: '1.18'
      RoleArn: >-
        arn:aws:iam::867975079432:role/uda-eks-service-role
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${myEnvName}-SecGrp"
        SubnetIds:
          - Fn::ImportValue: !Sub "${myEnvName}-SN1"
          - Fn::ImportValue: !Sub "${myEnvName}-SN2"
          - Fn::ImportValue: !Sub "${myEnvName}-SN3"
          - Fn::ImportValue: !Sub "${myEnvName}-SN4"

  Type: AWS::EKS::FargateProfile
  Properties:
    ClusterName: !GetAtt EKSCluster.Name
    FargateProfileName: Profile1
    PodExecutionRoleArn: String
    Selectors:
      - Selector
    Subnets:
      - String
    Tags:
      - Tag

Outputs:
  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksClusterRole.Arn
    Export:
      Name: !Sub {myEnvName}-RoleArn

  KSCluster:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${myEnvName}-EKSCluster